In [14]:
import pandas as pd
import numpy as np

chords = []
for r in range(1,9):
    x = pd.read_csv(f'./target/efc2_s105_day02_training_run{r}.tgt', sep='\t')
    print(np.unique(x['chordID']))
    chords.append(x['chordID'])

unique_values, counts = np.unique(chords, return_counts=True)
print(unique_values)
print(counts)


[12129 19111 29212 92122]
[12129 19111 29212 92122]
[12129 19111 29212 92122]
[12129 19111 29212 92122]
[12129 19111 29212 92122]
[12129 19111 29212 92122]
[19111 29212 92122]
[12129 29212 92122]
[12129 19111 29212 92122]
[100 100 100 100]
